# initialize our personal base image
FROM morehousej09/base

# now lets make sure that we have thrift installed
RUN apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev 


